spring:
  aop:
    proxyTargetClass: true

server:
  port: ${PORT:${SERVER_PORT:8040}}

zuul:
  ignoredServices: "*"
  add-proxy-headers: true
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    enroll:
      sensitiveHeaders:
      path: /enroll/**
      stripPrefix: false
    uaa:
      sensitiveHeaders:
      path: /uaa/**
      stripPrefix: false
    event: /events
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 60000
---
spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server/eureka/