version: '2'
services:
  authserver:
    build: ./authserver
    ports:
      - "8443:443"
  enroll-service:
    build: ./enroll-service
    ports:
      - "8080:80"
    links:
      - redis
  redis:
    image: redis:alpine    